

from alembic import op
import sqlalchemy as sa


revision = '19e4bffd7ee4'
down_revision = '63bd970c7ad0'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('nome_fantasia', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'nome_fantasia')
    # ### end Alembic commands ###