

from alembic import op
import sqlalchemy as sa


revision = '4f2094fe7647'
down_revision = 'c2b83a4cd1b4'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfops_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_operacao', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfops_transferencia_codigo'), 'cfops_transferencia', ['codigo'], unique=True)
    op.create_index(op.f('ix_cfops_transferencia_id'), 'cfops_transferencia', ['id'], unique=False)
    op.create_table('logs_processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('processo', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('dados_json', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.Text(), nullable=True),
    sa.Column('chave_nfe', sa.String(length=44), nullable=True),
    sa.Column('cnpj_empresa', sa.String(length=14), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_processamento_chave_nfe'), 'logs_processamento', ['chave_nfe'], unique=False)
    op.create_index(op.f('ix_logs_processamento_cnpj_empresa'), 'logs_processamento', ['cnpj_empresa'], unique=False)
    op.create_index(op.f('ix_logs_processamento_id'), 'logs_processamento', ['id'], unique=False)
    op.create_index(op.f('ix_logs_processamento_modulo'), 'logs_processamento', ['modulo'], unique=False)
    op.create_index(op.f('ix_logs_processamento_nivel'), 'logs_processamento', ['nivel'], unique=False)
    op.create_index(op.f('ix_logs_processamento_processo'), 'logs_processamento', ['processo'], unique=False)
    op.create_index(op.f('ix_logs_processamento_tag'), 'logs_processamento', ['tag'], unique=False)
    op.create_index(op.f('ix_logs_processamento_timestamp'), 'logs_processamento', ['timestamp'], unique=False)
    op.create_table('operacoes_pendentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_nfe', sa.String(length=44), nullable=False),
    sa.Column('cnpj_emissor', sa.String(length=14), nullable=False),
    sa.Column('cnpj_destinatario', sa.String(length=14), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=False),
    sa.Column('natureza_operacao', sa.Text(), nullable=False),
    sa.Column('tipo_sugerido', sa.String(length=20), nullable=True),
    sa.Column('motivo_pendencia', sa.Text(), nullable=False),
    sa.Column('tipo_definido', sa.String(length=20), nullable=True),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('resolvido_por', sa.String(length=50), nullable=True),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operacoes_pendentes_chave_nfe'), 'operacoes_pendentes', ['chave_nfe'], unique=False)
    op.create_index(op.f('ix_operacoes_pendentes_id'), 'operacoes_pendentes', ['id'], unique=False)
    op.create_table('remetentes_cadastrados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_cpf', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ie', sa.String(length=20), nullable=True),
    sa.Column('im', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remetentes_cadastrados_cnpj_cpf'), 'remetentes_cadastrados', ['cnpj_cpf'], unique=True)
    op.create_index(op.f('ix_remetentes_cadastrados_id'), 'remetentes_cadastrados', ['id'], unique=False)
    op.create_index(op.f('ix_remetentes_cadastrados_tipo'), 'remetentes_cadastrados', ['tipo'], unique=False)
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_documento_codigo'), 'tipo_documento', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipo_documento_id'), 'tipo_documento', ['id'], unique=False)
    op.add_column('certificados', sa.Column('cnpj', sa.String(), nullable=True))
    op.add_column('certificados', sa.Column('pfx_file', sa.LargeBinary(), nullable=True))
    op.add_column('certificados', sa.Column('pfx_password_encrypted', sa.String(), nullable=True))
    op.alter_column('certificados', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('certificados', 'tipo',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'A1'::character varying"))
    op.alter_column('certificados', 'pfx_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('certificados', 'senha_cripto',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_certificados_cnpj'), 'certificados', ['cnpj'], unique=True)
    op.create_index(op.f('ix_certificados_id'), 'certificados', ['id'], unique=False)
    op.add_column('dfe_documentos', sa.Column('tipo_documento_id', sa.Integer(), nullable=True))
    op.add_column('dfe_documentos', sa.Column('cnpj_emissor', sa.String(length=14), nullable=True))
    op.add_column('dfe_documentos', sa.Column('cnpj_destinatario', sa.String(length=14), nullable=True))
    op.add_column('dfe_documentos', sa.Column('data_emissao', sa.Date(), nullable=True))
    op.add_column('dfe_documentos', sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('dfe_documentos', sa.Column('numero_documento', sa.String(length=20), nullable=True))
    op.add_column('dfe_documentos', sa.Column('serie', sa.String(length=10), nullable=True))
    op.add_column('dfe_documentos', sa.Column('modelo', sa.String(length=5), nullable=True))
    op.add_column('dfe_documentos', sa.Column('natureza_operacao', sa.String(length=100), nullable=True))
    op.add_column('dfe_documentos', sa.Column('arquivo_origem', sa.Text(), nullable=True))
    op.create_index(op.f('ix_dfe_documentos_chave'), 'dfe_documentos', ['chave'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_cnpj_destinatario'), 'dfe_documentos', ['cnpj_destinatario'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_cnpj_emissor'), 'dfe_documentos', ['cnpj_emissor'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_data_emissao'), 'dfe_documentos', ['data_emissao'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_empresa_id'), 'dfe_documentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_nsu'), 'dfe_documentos', ['nsu'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_numero_documento'), 'dfe_documentos', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_dfe_documentos_tipo_documento_id'), 'dfe_documentos', ['tipo_documento_id'], unique=False)
    op.create_foreign_key(None, 'dfe_documentos', 'tipo_documento', ['tipo_documento_id'], ['id'])
    op.add_column('empresas', sa.Column('monitorada', sa.Boolean(), nullable=False))
    op.drop_constraint('empresas_cnpj_key', 'empresas', type_='unique')
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.create_unique_constraint('empresas_cnpj_key', 'empresas', ['cnpj'])
    op.drop_column('empresas', 'monitorada')
    op.drop_constraint(None, 'dfe_documentos', type_='foreignkey')
    op.drop_index(op.f('ix_dfe_documentos_tipo_documento_id'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_numero_documento'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_nsu'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_empresa_id'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_data_emissao'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_cnpj_emissor'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_cnpj_destinatario'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_chave'), table_name='dfe_documentos')
    op.drop_column('dfe_documentos', 'arquivo_origem')
    op.drop_column('dfe_documentos', 'natureza_operacao')
    op.drop_column('dfe_documentos', 'modelo')
    op.drop_column('dfe_documentos', 'serie')
    op.drop_column('dfe_documentos', 'numero_documento')
    op.drop_column('dfe_documentos', 'valor_total')
    op.drop_column('dfe_documentos', 'data_emissao')
    op.drop_column('dfe_documentos', 'cnpj_destinatario')
    op.drop_column('dfe_documentos', 'cnpj_emissor')
    op.drop_column('dfe_documentos', 'tipo_documento_id')
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_index(op.f('ix_certificados_cnpj'), table_name='certificados')
    op.alter_column('certificados', 'senha_cripto',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('certificados', 'pfx_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('certificados', 'tipo',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'A1'::character varying"))
    op.alter_column('certificados', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('certificados', 'pfx_password_encrypted')
    op.drop_column('certificados', 'pfx_file')
    op.drop_column('certificados', 'cnpj')
    op.drop_index(op.f('ix_tipo_documento_id'), table_name='tipo_documento')
    op.drop_index(op.f('ix_tipo_documento_codigo'), table_name='tipo_documento')
    op.drop_table('tipo_documento')
    op.drop_index(op.f('ix_remetentes_cadastrados_tipo'), table_name='remetentes_cadastrados')
    op.drop_index(op.f('ix_remetentes_cadastrados_id'), table_name='remetentes_cadastrados')
    op.drop_index(op.f('ix_remetentes_cadastrados_cnpj_cpf'), table_name='remetentes_cadastrados')
    op.drop_table('remetentes_cadastrados')
    op.drop_index(op.f('ix_operacoes_pendentes_id'), table_name='operacoes_pendentes')
    op.drop_index(op.f('ix_operacoes_pendentes_chave_nfe'), table_name='operacoes_pendentes')
    op.drop_table('operacoes_pendentes')
    op.drop_index(op.f('ix_logs_processamento_timestamp'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_tag'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_processo'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_nivel'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_modulo'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_id'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_cnpj_empresa'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_chave_nfe'), table_name='logs_processamento')
    op.drop_table('logs_processamento')
    op.drop_index(op.f('ix_cfops_transferencia_id'), table_name='cfops_transferencia')
    op.drop_index(op.f('ix_cfops_transferencia_codigo'), table_name='cfops_transferencia')
    op.drop_table('cfops_transferencia')
    # ### end Alembic commands ###