

from alembic import op
import sqlalchemy as sa


revision = '7f83423e43db'
down_revision = 'eb685a6ca93b'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certificados_empresa', table_name='certificados')
    op.drop_index('ix_dfe_chave', table_name='dfe_documentos')
    op.drop_index('ix_dfe_tipo_documento', table_name='dfe_documentos')
    op.drop_index('ix_empresas_monitorada', table_name='empresas')
    op.drop_index('ix_logs_nivel', table_name='logs_processamento')
    op.drop_index('ix_logs_timestamp', table_name='logs_processamento')
    op.drop_index('ix_remetentes_cnpj', table_name='remetentes_cadastrados')
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_remetentes_cnpj', 'remetentes_cadastrados', ['cnpj_cpf'], unique=False)
    op.create_index('ix_logs_timestamp', 'logs_processamento', ['timestamp'], unique=False)
    op.create_index('ix_logs_nivel', 'logs_processamento', ['nivel'], unique=False)
    op.create_index('ix_empresas_monitorada', 'empresas', ['monitorada'], unique=False)
    op.create_index('ix_dfe_tipo_documento', 'dfe_documentos', ['tipo_documento_id'], unique=False)
    op.create_index('ix_dfe_chave', 'dfe_documentos', ['chave'], unique=False)
    op.create_index('ix_certificados_empresa', 'certificados', ['empresa_id'], unique=False)
    # ### end Alembic commands ###