"""add certificados table

Revision ID: add_certificados_001
Revises: 0001_init
Create Date: 2025-11-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_certificados_001'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('pfx_file', sa.LargeBinary(), nullable=False),
    sa.Column('pfx_password_encrypted', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_cnpj'), 'certificados', ['cnpj'], unique=True)
    op.create_index(op.f('ix_certificados_id'), 'certificados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_index(op.f('ix_certificados_cnpj'), table_name='certificados')
    op.drop_table('certificados')
    # ### end Alembic commands ###