

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'eb685a6ca93b'
down_revision = '19e4bffd7ee4'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('certificados', sa.Column('nome_empresa', sa.String(length=255), nullable=True))
    op.add_column('certificados', sa.Column('valido_de', sa.String(length=25), nullable=True))
    op.add_column('certificados', sa.Column('valido_ate', sa.String(length=25), nullable=True))
    op.add_column('certificados', sa.Column('status_validacao', sa.String(length=50), nullable=True))

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_documento_id'), table_name='tipo_documento')
    op.drop_index(op.f('ix_tipo_documento_codigo'), table_name='tipo_documento')
    op.create_unique_constraint('tipo_documento_codigo_key', 'tipo_documento', ['codigo'])
    op.drop_index(op.f('ix_remetentes_cadastrados_tipo'), table_name='remetentes_cadastrados')
    op.drop_index(op.f('ix_remetentes_cadastrados_id'), table_name='remetentes_cadastrados')
    op.drop_index(op.f('ix_remetentes_cadastrados_cnpj_cpf'), table_name='remetentes_cadastrados')
    op.create_unique_constraint('remetentes_cadastrados_cnpj_cpf_key', 'remetentes_cadastrados', ['cnpj_cpf'])
    op.create_index('ix_remetentes_tipo', 'remetentes_cadastrados', ['tipo'], unique=False)
    op.create_index('ix_remetentes_cnpj_cpf', 'remetentes_cadastrados', ['cnpj_cpf'], unique=False)
    op.create_index('ix_remetentes_cnpj', 'remetentes_cadastrados', ['cnpj_cpf'], unique=False)
    op.drop_index(op.f('ix_operacoes_pendentes_id'), table_name='operacoes_pendentes')
    op.drop_index(op.f('ix_operacoes_pendentes_chave_nfe'), table_name='operacoes_pendentes')
    op.create_index('ix_operacoes_resolvido', 'operacoes_pendentes', ['resolvido'], unique=False)
    op.create_index('ix_operacoes_chave', 'operacoes_pendentes', ['chave_nfe'], unique=False)
    op.drop_index(op.f('ix_logs_processamento_timestamp'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_tag'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_processo'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_nivel'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_modulo'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_id'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_cnpj_empresa'), table_name='logs_processamento')
    op.drop_index(op.f('ix_logs_processamento_chave_nfe'), table_name='logs_processamento')
    op.create_index('ix_logs_timestamp', 'logs_processamento', ['timestamp'], unique=False)
    op.create_index('ix_logs_processo', 'logs_processamento', ['processo'], unique=False)
    op.create_index('ix_logs_nivel', 'logs_processamento', ['nivel'], unique=False)
    op.create_index('ix_logs_modulo', 'logs_processamento', ['modulo'], unique=False)
    op.create_index('ix_logs_cnpj_empresa', 'logs_processamento', ['cnpj_empresa'], unique=False)
    op.create_index('ix_logs_chave_nfe', 'logs_processamento', ['chave_nfe'], unique=False)
    op.add_column('empresas', sa.Column('data_atualizacao', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('data_cadastro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('codigo_atividade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('id_grupo_empresarial', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('atividade_principal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('cnpj_matriz', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('situacao_cadastral', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('data_abertura', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('tipo_empresa', sa.VARCHAR(length=50), server_default=sa.text("'Jurídica'::character varying"), autoincrement=False, nullable=True))
    op.create_foreign_key('empresas_grupo_id_fkey', 'empresas', 'grupos_empresariais', ['id_grupo_empresarial'], ['id'])
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.create_index('ix_empresas_cnpj', 'empresas', ['cnpj'], unique=False)
    op.create_index('ix_empresas_monitorada', 'empresas', ['monitorada'], unique=False)
    op.create_unique_constraint('empresas_cnpj_key', 'empresas', ['cnpj'])
    op.alter_column('empresas', 'ativo',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('empresas', 'nome_fantasia',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('dfe_documentos', sa.Column('manifest_xml_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dfe_documentos', sa.Column('manifest_cstat', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('dfe_documentos', sa.Column('manifest_tp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('dfe_documentos', sa.Column('manifest_nseq', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dfe_documentos', sa.Column('manifest_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('dfe_documentos', sa.Column('manifest_xmotivo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dfe_documentos_tipo_documento_id'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_numero_documento'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_nsu'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_empresa_id'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_data_emissao'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_cnpj_emissor'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_cnpj_destinatario'), table_name='dfe_documentos')
    op.drop_index(op.f('ix_dfe_documentos_chave'), table_name='dfe_documentos')
    op.create_index('ix_dfe_tipo_documento', 'dfe_documentos', ['tipo_documento_id'], unique=False)
    op.create_index('ix_dfe_numero_documento', 'dfe_documentos', ['numero_documento'], unique=False)
    op.create_index('ix_dfe_data_emissao', 'dfe_documentos', ['data_emissao'], unique=False)
    op.create_index('ix_dfe_cnpj_emissor', 'dfe_documentos', ['cnpj_emissor'], unique=False)
    op.create_index('ix_dfe_cnpj_destinatario', 'dfe_documentos', ['cnpj_destinatario'], unique=False)
    op.create_index('ix_dfe_chave', 'dfe_documentos', ['chave'], unique=False)
    op.drop_index(op.f('ix_cfops_transferencia_id'), table_name='cfops_transferencia')
    op.drop_index(op.f('ix_cfops_transferencia_codigo'), table_name='cfops_transferencia')
    op.create_index('ix_cfops_codigo', 'cfops_transferencia', ['codigo'], unique=False)
    op.create_unique_constraint('cfops_transferencia_codigo_key', 'cfops_transferencia', ['codigo'])
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_index(op.f('ix_certificados_cnpj'), table_name='certificados')
    op.create_index('ix_certificados_cnpj', 'certificados', ['cnpj'], unique=False)
    op.create_index('ix_certificados_empresa_id', 'certificados', ['empresa_id'], unique=False)
    op.create_index('ix_certificados_empresa', 'certificados', ['empresa_id'], unique=False)
    op.create_unique_constraint('certificados_cnpj_key', 'certificados', ['cnpj'])
    op.drop_column('certificados', 'status_validacao')
    op.drop_column('certificados', 'valido_ate')
    op.drop_column('certificados', 'valido_de')
    op.drop_column('certificados', 'nome_empresa')
    op.create_table('certificados_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=2), server_default=sa.text("'A1'::character varying"), autoincrement=False, nullable=False),
    sa.Column('pfx_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha_cripto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='certificados_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='certificados_pkey')
    )
    op.create_table('usuarios_sistema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pode_alterar_ambiente', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pode_gerenciar_certificados', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pode_visualizar_logs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pode_executar_consultas', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ultimo_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_reset_senha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_expiracao_reset', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('configuracoes_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_sistema_pkey')
    )
    op.create_index('ix_usuarios_sistema_username', 'usuarios_sistema', ['username'], unique=True)
    op.create_index('ix_usuarios_sistema_id', 'usuarios_sistema', ['id'], unique=False)
    op.create_index('ix_usuarios_sistema_email', 'usuarios_sistema', ['email'], unique=True)
    op.create_table('sessoes_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_jwt', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('data_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_expiracao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessoes_usuario_pkey')
    )
    op.create_index('ix_sessoes_usuario_usuario_id', 'sessoes_usuario', ['usuario_id'], unique=False)
    op.create_index('ix_sessoes_usuario_id', 'sessoes_usuario', ['id'], unique=False)
    op.create_table('webservices_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('nome_estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('codigo_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('ambiente', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('suporta_nfe', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('suporta_nfce', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('suporta_cte', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('suporta_mdfe', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('url_nfe_autorizacao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_nfe_consulta', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_nfe_download', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_nfe_dist_dfe', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_nfe_status', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_cte_autorizacao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_cte_consulta', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_cte_download', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('versao_nfe', sa.VARCHAR(length=10), server_default=sa.text("'4.00'::character varying"), autoincrement=False, nullable=True),
    sa.Column('versao_cte', sa.VARCHAR(length=10), server_default=sa.text("'3.00'::character varying"), autoincrement=False, nullable=True),
    sa.Column('timeout_segundos', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('max_tentativas', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('status_ultimo_teste', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_ultimo_teste', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tempo_resposta_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ultima_mensagem_erro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='webservices_config_pkey')
    )
    op.create_index('idx_webservices_config_uf', 'webservices_config', ['uf'], unique=False)
    op.create_index('idx_webservices_config_ativo', 'webservices_config', ['ativo'], unique=False)
    op.create_index('idx_webservices_config_ambiente', 'webservices_config', ['ambiente'], unique=False)
    op.create_table('grupos_empresariais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_grupo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='grupos_empresariais_pkey')
    )
    op.create_table('certificados_digitais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnpj_titular', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nome_titular', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tipo_certificado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('emissor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_emissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('revogado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('arquivo_p12_criptografado', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('hash_senha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('senha_criptografada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('algoritmo_assinatura', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tamanho_chave', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('id_empresa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('cadastrado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_ultimo_uso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_usos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pfx_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('senha_cripto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='certificados_digitais_pkey')
    )
    # ### end Alembic commands ###